While working on partest discovered that Compil...
While working on partest discovered that CompilerCommand ignores half
its constructor arguments and a couple dozen places blithely pass it
those arguments as if they're being used. Then there were setups like
this:

class OfflineCompilerCommand(
  arguments: List[String],
  settings: Settings,
  error: String => Unit,
  interactive: Boolean)
extends CompilerCommand(arguments, new Settings(error), error, false)

Hey offline compiler command, why throw away the perfectly good settings
you were given? Ever heard 'reduce, reuse, recycle'? How did you ever
work... or do you? No review.